import type { Stock } from "@/interfaces/stock";
import type { HouseholdMember } from "@/interfaces/family";
import type { FeedTag } from "@/interfaces/stock";

export const sampleFeedTags: FeedTag[] = [
  {
    id: "tag_sample_milk",
    label: "配方奶",
    appliesToStockType: "infantStapleFood",
  },
  {
    id: "tag_sample_dogfood",
    label: "一般乾糧",
    appliesToStockType: "petStapleFood",
  },
  {
    id: "tag_sample_dogcan",
    label: "主食罐",
    appliesToStockType: "petStapleFood",
  }
];

export const sampleHouseholdData: HouseholdMember[] = [
  {
    id: "sample_1",
    identity: "adult",
    name: "爸爸",
    dailyKcalNeed: 2200,
    dailyMlWater: 2500,
  },
  {
    id: "sample_2",
    identity: "adult",
    name: "媽媽",
    dailyKcalNeed: 1800,
    dailyMlWater: 2000,
  },
  {
    id: "sample_3",
    identity: "child",
    name: "阿明",
    dailyKcalNeed: 1500,
    dailyMlWater: 1500,
  },
  {
    id: "sample_4",
    identity: "infant",
    name: "二寶",
    dailyMlWater: 500,
    feedPortions: [
      {
        feedTagId: "tag_sample_milk",
        amount: 800,
        unit: "ml",
        frequencyDays: 1,
      }
    ]
  },
  {
    id: "sample_5",
    identity: "pet",
    name: "狗狗 (布丁)",
    dailyMlWater: 500,
    feedPortions: [
      {
        feedTagId: "tag_sample_dogfood",
        amount: 150,
        unit: "g",
        frequencyDays: 1,
      },
      {
        feedTagId: "tag_sample_dogcan",
        amount: 1,
        unit: "unit",
        frequencyDays: 7,
      }
    ]
  }
];

export const sampleStockData: Stock[] = [
  {
    id: "sample-001",
    name: "飲用水",
    type: "water",
    count: 114,
    unit: "bottle",
    expirationDate: "2027-06-30",
    purchaseDate: "",
    remark: "建議每人每天 3 公升",
    totalCalories: undefined,
    volume: 600,
  },
  {
    id: "sample-002",
    name: "罐頭",
    type: "food",
    count: 16,
    unit: "can",
    expirationDate: "2026-03-31",
    purchaseDate: "",
    remark: "不用煮的主食",
    totalCalories: 1500,
    volume: undefined,
  },
  {
    id: "sample-003",
    name: "營養棒",
    type: "food",
    count: 8,
    unit: "pack",
    expirationDate: "2026-12-31",
    purchaseDate: "",
    remark: "能量點心，快速補充熱量",
    totalCalories: 1600,
    volume: undefined,
  },
  {
    id: "sample-004",
    name: "調理包",
    type: "food",
    count: 4,
    unit: "pack",
    expirationDate: "2027-01-31",
    purchaseDate: "",
    remark: "簡單煮的主食",
    totalCalories: 2400,
    volume: undefined,
  },
  {
    id: "sample-005",
    name: "食用油",
    type: "food",
    count: 0,
    unit: "bottle",
    expirationDate: "",
    purchaseDate: "",
    remark: "基本調味料",
    totalCalories: undefined,
    volume: 600,
  },
  {
    id: "sample-006",
    name: "口罩",
    type: "medical",
    count: 120,
    unit: "piece",
    expirationDate: "2028-12-31",
    purchaseDate: "",
    remark: "衛生用品",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-007",
    name: "衛生紙",
    type: "other",
    count: 16,
    unit: "pack",
    expirationDate: "",
    purchaseDate: "",
    remark: "衛生用品",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-008",
    name: "消毒濕紙巾",
    type: "medical",
    count: 13,
    unit: "pack",
    expirationDate: "2026-09-30",
    purchaseDate: "",
    remark: "消毒濕紙巾、酒精噴霧",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-009",
    name: "女性生理用品",
    type: "other",
    count: 12,
    unit: "pack",
    expirationDate: "",
    purchaseDate: "",
    remark: "依需求準備",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-010",
    name: "濾水工具",
    type: "tool",
    count: 11,
    unit: "piece",
    expirationDate: "",
    purchaseDate: "",
    remark: "衛生用品",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-011",
    name: "藥膏",
    type: "medical",
    count: 11,
    unit: "piece",
    expirationDate: "2026-07-31",
    purchaseDate: "",
    remark: "急救箱內容物",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-012",
    name: "常用藥物",
    type: "medical",
    count: 11,
    unit: "pack",
    expirationDate: "",
    purchaseDate: "",
    remark: "個人處方藥請依實際需求補充",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-013",
    name: "備用眼鏡",
    type: "other",
    count: 11,
    unit: "piece",
    expirationDate: "",
    purchaseDate: "",
    remark: "如有需要",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-017",
    name: "乾電池",
    type: "tool",
    count: 18,
    unit: "piece",
    expirationDate: "",
    purchaseDate: "",
    remark: "請注意電池型號",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-018",
    name: "充電線",
    type: "tool",
    count: 12,
    unit: "piece",
    expirationDate: "",
    purchaseDate: "",
    remark: "手機等設備充電用",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-019",
    name: "行動電源",
    type: "tool",
    count: 11,
    unit: "piece",
    expirationDate: "",
    purchaseDate: "",
    remark: "充飽的備用電源",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-020",
    name: "小型手搖發電機",
    type: "tool",
    count: 11,
    unit: "piece",
    expirationDate: "",
    purchaseDate: "",
    remark: "行動電源沒電時緊急充電",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-021",
    name: "工作手套",
    type: "tool",
    count: 11,
    unit: "pair",
    expirationDate: "",
    purchaseDate: "",
    remark: "防切割、耐磨",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-022",
    name: "塑膠袋",
    type: "other",
    count: 110,
    unit: "piece",
    expirationDate: "",
    purchaseDate: "",
    remark: "隔離垃圾、保持衛生、防水包裹物品",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-023",
    name: "保鮮膜",
    type: "other",
    count: 11,
    unit: "roll",
    expirationDate: "",
    purchaseDate: "",
    remark: "包裹食物或覆蓋傷口",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-024",
    name: "卡式爐",
    type: "tool",
    count: 11,
    unit: "piece",
    expirationDate: "",
    purchaseDate: "",
    remark: "停電時可簡單烹煮",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample-025",
    name: "布質膠帶",
    type: "tool",
    count: 11,
    unit: "roll",
    expirationDate: "",
    purchaseDate: "",
    remark: "隔絕、固定封裝或簡易修復",
    totalCalories: undefined,
    volume: undefined,
  },
  {
    id: "sample_milk_1",
    name: "雀巢能恩水解配方奶",
    type: "infantStapleFood",
    count: 3,
    unit: "can",
    volume: 800,
    volumeUnit: "g",
    expirationDate: "2026-12-31",
    purchaseDate: "2024-05-01",
    feedTagId: "tag_sample_milk",
    remark: "二寶主食",
    totalCalories: undefined,
  },
  {
    id: "sample_dogfood_1",
    name: "皇家狗狗乾糧 5kg",
    type: "petStapleFood",
    count: 2,
    unit: "pack",
    volume: 5000,
    volumeUnit: "g",
    expirationDate: "2025-10-31",
    purchaseDate: "2024-06-15",
    feedTagId: "tag_sample_dogfood",
    remark: "布丁的主食乾糧",
    totalCalories: undefined,
  },
  {
    id: "sample_dogcan_1",
    name: "西莎 皇冠主食罐",
    type: "petStapleFood",
    count: 12,
    unit: "can",
    volume: 1,
    volumeUnit: "unit",
    expirationDate: "2026-02-28",
    purchaseDate: "2024-07-01",
    feedTagId: "tag_sample_dogcan",
    remark: "布丁的主食罐頭",
    totalCalories: undefined,
  },
  {
    id: "sample-028",
    name: "亞培安素",
    type: "food",
    count: 11,
    unit: "pack",
    expirationDate: "2026-08-31",
    purchaseDate: "",
    remark: "年長者用品，如有需要",
    totalCalories: undefined,
    volume: undefined,
  },
];